// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.4.1 on 2020-09-09T12:26:23.043Z

const awsmobile = {
    aws_cloud_logic_custom: [
        {
            endpoint: 'https://z236nz20u1.execute-api.us-east-1.amazonaws.com/dev',
            name: 'ApiGatewayRestApi',
            region: 'us-east-1'
        }
    ],
    aws_cognito_identity_pool_id: 'us-east-1:6db6de33-181b-4fcc-ada2-172dd5d868ce',
    aws_cognito_region: 'us-east-1',
    aws_project_region: 'us-east-1'
};

export default awsmobile;

export default {
    apiGateway: {
      REGION: "us-east-1",
      URL: "https://z236nz20u1.execute-api.us-east-1.amazonaws.com/dev"
    },
    cognito: {
      REGION: "us-east-1",
      USER_POOL_ID: "us-east-1_7Oj3wCMsO",
      APP_CLIENT_ID: "1sh5634aqgebf88viiskm05qgp",
      IDENTITY_POOL_ID: "us-east-1:6db6de33-181b-4fcc-ada2-172dd5d868ce"
    }
};
